const marketSeries={
  nifty:{title:'NIFTY 50',image:'nifty-trend.svg',latest:'24,207',asof:'July 2026',note:'Indian large-cap equity benchmark.'},
  gold:{title:'22K Gold · India',image:'gold-india-trend.svg',latest:'₹13,583 per g',asof:'July 2026',note:'Indicative 22K metal value using 15% import tariff and 3% GST; before premium and making charges.'},
  fed:{title:'Effective Federal Funds Rate',image:'fed-rate-trend.svg',latest:'3.63%',asof:'June 2026',note:'Official monthly U.S. Federal Reserve series.'},
  dxy:{title:'U.S. Dollar Index',image:'dollar-index-trend.svg',latest:'101.08',asof:'July 2026',note:'Dollar index historical trend.'}
};
const liveLinks={nifty:['https://www.google.com/finance/quote/NIFTY_50:INDEXNSE','Open live NIFTY on Google Finance ↗'],gold:['https://www.google.com/finance/quote/GCW00:COMEX','Open live international gold ↗'],fed:['https://fred.stlouisfed.org/series/FEDFUNDS','Open official Fed series ↗'],dxy:['https://www.google.com/finance/quote/DXY:INDEXNYSEGIS','Open live dollar index ↗']};
function loadMarket(key){const item=marketSeries[key];if(!item)return;const image=document.getElementById('market-image');image.src=item.image;image.alt=item.title+' trend from 2011 to 2026';document.getElementById('market-title').textContent=item.title;document.getElementById('market-value').textContent=item.latest;document.getElementById('market-asof').textContent='Latest observation: '+item.asof;document.getElementById('market-note').textContent=item.note;const link=document.getElementById('market-live-link');link.href=liveLinks[key][0];link.textContent=liveLinks[key][1];document.querySelectorAll('.market-tab').forEach(button=>{const active=button.dataset.market===key;button.classList.toggle('active',active);button.setAttribute('aria-selected',active)});}
function calculateGold(){const usd=+document.getElementById('gold-usd').value||0,fx=+document.getElementById('usd-inr').value||0,duty=(+document.getElementById('gold-duty').value||0)/100,gst=(+document.getElementById('gold-gst').value||0)/100,premium=(+document.getElementById('dealer-premium').value||0)/100,making=+document.getElementById('making-charge').value||0;const base24=usd*fx/31.1034768,landed22=base24*(1+duty)*(22/24),metal=landed22*(1+premium)*(1+gst),shop=metal+making*1.05;document.getElementById('gold-base-result').textContent='₹'+Math.round(metal).toLocaleString('en-IN')+' / g';document.getElementById('gold-shop-result').textContent='₹'+Math.round(shop).toLocaleString('en-IN')+' / g';}
document.querySelectorAll('.market-tab').forEach(button=>button.addEventListener('click',()=>loadMarket(button.dataset.market)));document.querySelectorAll('.gold-input').forEach(input=>input.addEventListener('input',calculateGold));let fedWidgetLoaded=false;const fedDetails=document.getElementById('fed-live');if(fedDetails)fedDetails.addEventListener('toggle',()=>{if(!fedDetails.open||fedWidgetLoaded||typeof TradingView==='undefined')return;fedWidgetLoaded=true;new TradingView.widget({autosize:true,symbol:'FRED:FEDFUNDS',interval:'M',timezone:'Etc/UTC',theme:'light',style:'1',locale:'en',allow_symbol_change:false,hide_side_toolbar:true,withdateranges:true,range:'ALL',container_id:'fed-widget'});});loadMarket('nifty');calculateGold();
